runtime: nodejs18

env_variables:
  CLOUDINARY_CLOUD_NAME: "YOUR_CLOUDINARY_CLOUD_NAME"
  CLOUDINARY_API_KEY: "YOUR_CLOUDINARY_API_KEY"
  CLOUDINARY_API_SECRET: "YOUR_CLOUDINARY_API_SECRET"

automatic_scaling:
  min_instances: 1
  max_instances: 10

